name: Main

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    matrix:
      os:
        - ubuntu-latest
        - macOS-latest
      cabal:
        - "3.6.2.0"
      ghc:
        - "9.2.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1.2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Build
        run: cabal install exe:tie --install-method=copy --overwrite-policy=always --installdir=out

      - name: Test
        run: ./out/tie --help

      - name: Prepare archive
        run: tar -zcvf ./${{ matrix.os }}.tar.gz -C out tie

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./${{ matrix.os }}.tar.gz
